### ISSUE TITLE
Create video with walkthrough and explanation of the app we can send to people who are wondering about how the app works.

### ISSUE THREAD

**Issue by Zikoat** [bcc-code/buk-universal-games#101]
Bård sent a message if we can create a video about how the app works. I am not quite sure if he meant for referees or for participants, so maybe create 2 different videos?

**Comment by kris10anebratlie** [comment]
@Zikoat blocked by #76

**Comment by kris10anebratlie** [comment]
@Zikoat insert photos of zones
