### ISSUE TITLE
Update pages and logos for each game type

### ISSUE THREAD

**Issue by Zikoat** [bcc-code/buk-universal-games#42]
![image](https://github.com/bcc-code/buk-universal-games/assets/10808413/f9620dcd-6905-4673-b7a1-6640cc99077f)

[Postbeskrivelser UBG 2024.docx](https://github.com/bcc-code/buk-universal-games/files/14893901/Postbeskrivelser.UBG.2024.docx)

**Comment by Zikoat** [comment]
We only need to add the info for the players. Admins will get a separate paper with instructions on how to count scores, so we dont have to add that to the game instructions.

**Comment by kris10anebratlie** [comment]
@Zikoat waiting for this from marit and bård
