### ISSUE TITLE
Select zone and game type when logging in as admin

### ISSUE THREAD

**Issue by Zikoat** [bcc-code/buk-universal-games#65]
When a user logs in as an admin (dommer), then they should first get asked which zone they are in, and then in which game type they are admin for. 
When they have selected both, they should end up in the match list. It currently sends them to the leaderboard, but they should be sent to the match list instead.

![image](https://github.com/bcc-code/buk-universal-games/assets/10808413/a5690bd1-981e-4c30-b2c0-7cc21c6ae740)

**Comment by kris10anebratlie** [comment]
@Zikoat this can be closed?
