### ISSUE TITLE
k --> million and balance --> M EURO

### ISSUE THREAD

**Issue by kris10anebratlie** [bcc-code/buk-universal-games#72]
Change all places it says k to M (from 1000 to million)

![IMG_6508](https://github.com/bcc-code/buk-universal-games/assets/117045349/a8e9d60c-d000-4451-b141-60a33cb89ba3)

**Comment by Zikoat** [comment]
Have to check with bård what is preferred here.

**Comment by Zikoat** [comment]
![image](https://github.com/user-attachments/assets/895bc858-8942-459a-a8af-eda173de4e83)

Updated this in commit cddce9d0e9a59aa12984b963a8002ebda03d9faf

**Comment by Zikoat** [comment]
![image](https://github.com/user-attachments/assets/bff5c285-59bf-4e0e-bfe4-baaaf544a9a6)
