### ISSUE TITLE
Point registration

### ISSUE THREAD

**Issue by kris10anebratlie** [bcc-code/buk-universal-games#75]
- [ ] **Land Water Beach** (two teams)

Judge: Should enter the number of rounds with points. There are 9 rounds of 3 points each, so a maximum of 27 points.
Frontend: This needs to be scaled, so perhaps multiply by "number of completed rounds"*(20/27)

**Iron Grip** (1 team)
Judge: Records total hang time
Frontend: Registers points from minimum to maximum time, predefined points and time intervals. Case when statement.

**Hamster Wheel (this needs clarification)** (two teams)
Judge: Record how many rounds each team won. It's best of 3
Frontend:
5 points per round won
5 points for winning

**Mastermind** (1 team)
Judge: Record the number of steps they took to complete it. There are 3 rounds, so they must register the total.
Frontend: steps to points

**Labyrinth** (not sure)
Judge: First record the number of checkpoints, if checkpoints == 3 then record time
Frontend: Not sure

**Comment by Zikoat** [comment]
## hamsterhjul

Hamsterhjul må være samme meter og antall folk i hamsterhjulet.

For hver gang spillerne går utenfor duken får man -10 sekunder. Dommerne må altså i tillegg registrere antall strikes.

## land vann strand

3 x 3 runder. Spillere bytter mellom runder. 

dommer kommer til å telle poeng med en tavle, og skrive det inn i appen etterpå.

## labyrint

Noen poster kan ha 2 labyrinter (altså ikke flere poster, men flere labyrinter per post) for store grupper slik at det er flere deltakere. da skal man registrere tidsbruken på BEGGE labyrintene og ta gjennomsnittet av de. Det er kun 1 dommer som registrerer poeng for begge labyrintene. Litt på samme måte som for Iron grip.

## mastermind

10p gis om laget klarer å løse koden ila 2 rader. 
8p = ila 4 rader 
6p = ila 6 rader 
4p = ila 8 rader 
2p = hvis noen farger riktig plassert. (1-3 rød på den 8. runda)
0p = ingen farger riktig plassert (0 rød på den 8. runda)

IKKE flere runder, kun 1 gjennomgang.

## Jerngrepet
Tid og antall juks.

**Comment by Zikoat** [comment]
Bård skal ha Manus til dommere, og ekstra regler til dommere, og detaljerte poeng-registrerings beskrivelser klart til søndag 9. Juni.

**Comment by Zikoat** [comment]
https://vue3datepicker.com/props/time-picker-configuration/
