### ISSUE TITLE
Import matches and teams

### ISSUE THREAD

**Issue by kris10anebratlie** [bcc-code/buk-universal-games#76]
- [ ] Test import
- [ ] Make changes from Bård/planning group easier and smooth

**Comment by Zikoat** [comment]
The team names and other info is in sharepoint > 2435 BUK Sommercamp > 30_Samarbeid_LM > 04 BCC Hamar > 09_UBG > 01_Konsept > Lagfordeling og kjøreplan_UBGSC24.xlsx

**Comment by kris10anebratlie** [comment]
BLOCKED
