### ISSUE TITLE
Fix http issue

### ISSUE THREAD

**Issue by kris10anebratlie** [bcc-code/buk-universal-games#77]

**Comment by Zikoat** [comment]
If the http type isn't specified on iphone safari, then it says couldn't load page.
If specifically http is used on mac safari, then it says couldn't load the page.
I currently don't have an iphone or mac to test this with, but i will find one.

**Comment by Zikoat** [comment]
Kristiane can unsubscribe to notifications here.

**Comment by Zikoat** [comment]
So i haven't been able to figure out yet what the cause of this is, or how i can fix it.
We can workaround this by just adding https:// to the beginning of the urls.

**Comment by Zikoat** [comment]
Closing. Will use workaround.
