### ISSUE TITLE
Two teams point registration

### ISSUE THREAD

**Issue by kris10anebratlie** [bcc-code/buk-universal-games#78]
When registrering points for two teams, both teams values needs to be filled before confirming result. Otherwise it will be buggy deciding and giving extra points for winner

**Comment by Zikoat** [comment]
We should also handle draw.

**Comment by kris10anebratlie** [comment]
What does this mean

**Comment by Zikoat** [comment]
For example on land, water, beach, each team can get the same amount of points, which means that there won't be shown a winner or a loser, but we should probably show "draw" in the results screen.
