### ISSUE TITLE
Make match card transparent not grey when passed / scores filled

### ISSUE THREAD

**Issue by kris10anebratlie** [bcc-code/buk-universal-games#85]
![image](https://github.com/bcc-code/buk-universal-games/assets/117045349/332d0acc-052a-4ea5-a2b4-e90627211968)

**Comment by Zikoat** [comment]
a616a038e069d385df3170f89df1a6e4f6670771
![image](https://github.com/bcc-code/buk-universal-games/assets/10808413/706771d5-bc70-4eb7-b663-57ff196708dc)
