### ISSUE TITLE
Create channel with team code links

### ISSUE THREAD

**Issue by Zikoat** [bcc-code/buk-universal-games#88]
We should create the messages that should be sent to the teams so they can log into the app. Instead of sending the message as a user, we can create a telegram channel and post the messages as that channel. That way the "sender" of the message is the channel name. Then we can add bård or elise bekkevold so they can forward the messages.

**Comment by Zikoat** [comment]
@kris10anebratlie Can you create the telegram messages that should be sent?

**Comment by Zikoat** [comment]
The codes were previously in sharepoint > 2435 BUK Sommercamp > 30_Samarbeid_LM > 04 BCC Hamar > 09_UBG > 01_Konsept > Lagfordeling og kjøreplan_UBGSC24.xlsx 

However the codes there are gone now. You probably have to generate new codes. They can just be a random string of 6 letters and numbers.

**Comment by kris10anebratlie** [comment]
@Zikoat done
