### ISSUE TITLE
Custom color for each family

### ISSUE THREAD

**Issue by Zikoat** [bcc-code/buk-universal-games#94]

**Comment by Zikoat** [comment]
@kris10anebratlie Could you maybe add in the figma a custom color to the leaderboard for each family? I think the colors have some significance. see attachment with the colors for the teams. 

[240410 Lagfordeling og kjøreplan_UBGSC24.pdf](https://github.com/user-attachments/files/16168083/240410.Lagfordeling.og.kjoreplan_UBGSC24.pdf)

**Comment by kris10anebratlie** [comment]
@Zikoat it is iadded in directus and in excel just need an import
![Screenshot 2024-07-12 at 19 31 51](https://github.com/user-attachments/assets/b2c1e92a-4679-40f8-89eb-9550622a102c)
![Screenshot 2024-07-12 at 19 32 09](https://github.com/user-attachments/assets/de5cb738-af85-4665-a0f9-750d201065ae)

**Comment by kris10anebratlie** [comment]
BLOCKED by #76

**Comment by Zikoat** [comment]
imma add the custom color to the leaderboard header, maybe color the icon and text, or the background.

**Comment by Zikoat** [comment]
![image](https://github.com/user-attachments/assets/3d65e4d4-9f15-4487-90e6-3e3f1f46264d)
![image](https://github.com/user-attachments/assets/17600772-df2d-412d-ba2d-eb9a0f9d64d5)
![image](https://github.com/user-attachments/assets/b19f33d8-9fe7-4633-970a-de02d022112d)
![image](https://github.com/user-attachments/assets/f2f8d630-22e1-40ed-89eb-81c8ba12c6e8)

ok @kris10anebratlie ?
