### ISSUE TITLE
Create backup google forms

### ISSUE THREAD

**Issue by Zikoat** [bcc-code/buk-universal-games#98]
Worst-case scenario is that the app doesn't work at all, and referees have to send scores through another medium. We need a backup plan for this. We have telegram groups for each game type where referees can send messages, but BCC Event mentioned that maybe a google form would be more structured, and easier for collecting scores in case the app doesn't work.

**Comment by Zikoat** [comment]
@kris10anebratlie Colud you create a simple plan for this, just in case the worst happens?

**Comment by kris10anebratlie** [comment]
@Zikoat not sure I have time for this issue :((

**Comment by Zikoat** [comment]
Bård did
